language: python
matrix:
  include:
  - os: linux
    python: 2.7
    env: TOKENV=py27 TESTMODE=full COVERAGE=--coverage
  - os: linux
    python: 3.4
    env: TOKENV=py34 TESTMODE=full COVERAGE=--coverage
  - os: osx
    language: generic
    env: TOKENV=py27 TESTMODE=full COVERAGE=--coverage
  - os: osx
    language: generic
    env: TOKENV=py35 TESTMODE=full COVERAGE=--coverage
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source .linux_build.sh $TOKENV $TESTMODE;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  source .osx_build.sh $TOKENV; fi
script:
- flake8 *.py sima --exclude sima/misc/tifffile.py,sima/__init__.py,test*.py,sima/motion/__init__.py,sima/segment/__init__.py
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python runtests.py --doctests -m $TESTMODE
  $COVERAGE; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py27" ]]; then python runtests.py
  --doctests -m $TESTMODE $COVERAGE; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py35" ]]; then python3 runtests.py
  --doctests -m $TESTMODE $COVERAGE; fi
- cd doc && make html && cd ..
branches:
  only:
  - master
  - 0.3.x
  - 1.0.x
  - 1.1.x
  - 1.3.x
deploy:
  provider: s3
  bucket: jdz2110.travis
  secret_access_key:
    secure: HDEeMrrCIUyGgDNDBpzgmDabKWrK8mc+F7XY5l4rZLwD/CkpETYWUveNkqvvSM8Vkt/aA04l2u+sLN8agZ26UTOnL9iTZP5VaSTw8tdvtqZZ6VCW5JSJ7Y2VqPtEG3afxXf91eno1KOejvmFY87QkwTnAbJya2yToPacuoNVQRc=
  access_key_id: AKIAJGVHLWIG37JT6RLA
  skip_cleanup: true
  upload-dir: ${TRAVIS_OS_NAME}_${TOKENV}
after_success:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then if [ "${TESTMODE}" == "full" ];
  then cp build/test/.coverage . && coveralls; fi; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py bdist_whl; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py27" ]]; then python setup.py bdist_whl; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py35" ]]; then python3 setup.py bdist_whl; fi
