language: python
env:
  global:
    # AWS keys
    - secure: "hWFDIYzWLfvsVuF5YgdEunz9BU6N1O/ZoM9h4ucwYU+UGx5nCuTM9apuFQX3Ox+FR3HnFrhE6JEFWa1RVjyusdik4huouYdCJmyyEC1Ot3UCsJST3lVDiZh8QLn1AyLIDUdhe3Hx/gF1H6zufGWtjQRzcA3/CKEcu0at+gB1o5M="
    - secure: "I4MgDeVY+P3MbBhdJqTb5jhearGruGBpVGpNW2rqRifan9mLMxr9zQurQY8LiGr8kbpAjP3KTHb5XCPDyL8uFcTSUmwH4c9wFfl4tqBKGnf15PKysohhHRtIBhWKQYJbPaps4PYO0Abqq5iYO5A8lOqpcLnfL/ACMP+abUPG+M4="
matrix:
  include:
  - os: linux
    python: 2.7
    env: TOKENV=py27 TESTMODE=full COVERAGE=--coverage
  - os: linux
    python: 3.4
    env: TOKENV=py34 TESTMODE=full COVERAGE=--coverage
  - os: osx
    language: generic
    env: TOKENV=py27 TESTMODE=full COVERAGE=--coverage
  - os: osx
    language: generic
    env: TOKENV=py35 TESTMODE=full COVERAGE=--coverage
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source .linux_build.sh $TOKENV $TESTMODE;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  source .osx_build.sh $TOKENV; fi
script:
- flake8 *.py sima --exclude sima/misc/tifffile.py,sima/__init__.py,test*.py,sima/motion/__init__.py,sima/segment/__init__.py
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python runtests.py --doctests -m $TESTMODE
  $COVERAGE; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py27" ]]; then python runtests.py
  --doctests -m $TESTMODE $COVERAGE; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py35" ]]; then python3 runtests.py
  --doctests -m $TESTMODE $COVERAGE; fi
branches:
  only:
  - master
  - 0.3.x
  - 1.0.x
  - 1.1.x
  - 1.3.x
after_success:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then if [ "${TESTMODE}" == "full" ];
  then cp build/test/.coverage . && coveralls; fi; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install wheel && python setup.py bdist_wheel; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py27" ]]; then pip install wheel && python setup.py bdist_wheel; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOKENV" == "py35" ]]; then pip3 install wheel && python3 setup.py bdist_wheel; fi
- if [[ "$TRAVIS_REPO_SLUG" == "losonczylab/sima" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_OS_NAME" == "osx" && "$TOKENV" == "py35" ]]; then pip3 install awscli && aws s3 cp dist s3://jdz2110.travis/${TRAVIS_OS_NAME}_${TOKENV} --recursive; fi
- if [[ "$TRAVIS_REPO_SLUG" == "losonczylab/sima" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_OS_NAME" != "osx" || "$TOKENV" != "py35" ]]; then pip install awscli && aws s3 cp dist s3://jdz2110.travis/${TRAVIS_OS_NAME}_${TOKENV} --recursive; fi
